### ISSUE TITLE
[tentacle] Extra Large Text e.g. Intro and Newspaper Titles Missing

### ISSUE THREAD

**Issue by Dor-Tumarkin** [adventurebrew/scummworks#14]
Titles on large fonts are missing, a single Beta character appears instead.

**Comment by BLooperZ** [comment]
Hi, thank for the report, did you downloaded this release?https://github.com/adventurebrew/scummworks/releases/tag/DOTT-WIP2

**Comment by Dor-Tumarkin** [comment]
Hey, thanks for the response, it works well in the intro, so I guess the newer version is fixed...

But I won't be updating. משוש? That's awful, it was טנטקל in the previous version, that was the original translation on the game's box and that is their name. I'd rather have a broken version than a translation that feels wrong. I am sorry to say it's as bad as Barnashtzeva, another translation I passed on.

I love what you guys do and really appreciate it, but hate how you change names like this. Names are names, they shouldn't be translated. That would be like an English speaker calling you Fang Clarify, it makes no sense.

Sorry, I know, I am being ungrateful. You're doing something truly incredible and I just wish you did it while respecting the characters more than the need to translate everything literally.

Thanks for the response and the work.
