### ISSUE TITLE
comi: Missing translation on gondola animation

### ISSUE THREAD

**Issue by orgads** [adventurebrew/scummworks#7]
When the door is opened, the animation is not translated. [Saved game](https://github.com/adventurebrew/scummworks/files/6033803/anim.zip)

**Comment by BLooperZ** [comment]
It seems the door opening animation sequence is a costume (AKOS 402) .
The extraction currently results in messed up palette, but after replacing it with palette from room background it looks ok.
Working on the tools to add support for importing costumes (luckily, we can ignore the palette completely for this part).
